name: hdcrs

channels:
  - conda-forge

dependencies:
  - python=3.9
  - dask[complete]
  - dask-jobqueue
  - jupyterlab>=3
  - dask-labextension
  - jupyterlab-git
  - gdal
  - xarray
  - rioxarray
  - matplotlib 
  - h5netcdf
  - zarr
  - shapely
  - fsspec
  - panel
  - pystac
  - pystac-client
  - python-graphviz
  - pip
  - pip:
    - dcachefs>=0.1.7
    - stac2dcache

